### ISSUE TITLE
gradle-wrapper.properties should be included in repo

### ISSUE THREAD

**Issue by JobaerChowdhury** [simantaturja/CRUD-REST-API-SpringBoot#2]
It should not be excluded I think. To make sure all the devs have same gradle version.

**Comment by simantaturja** [comment]
Should gradle-wrapper.jar also be included?

**Comment by JobaerChowdhury** [comment]
> Should gradle-wrapper.jar also be included?

This I am not sure. Please try to find out what is the best practice here.
