### ISSUE TITLE
What would happen if the save operation fails for some reason?

### ISSUE THREAD

**Issue by JobaerChowdhury** [simantaturja/CRUD-REST-API-SpringBoot#3]
https://github.com/simantaturja/CRUD-REST-API-SpringBoot/blob/01a783634013147cf848bb8595a8b029e2795376/src/main/java/com/example/crudrestapi/controller/AuthorController.java#L47

**Comment by simantaturja** [comment]
I covered up all the cases manually except the system failure. So, it will return 500 error by default in case of failing. Should I use a try catch block and manually throw an error?

**Comment by JobaerChowdhury** [comment]
In this specific case 500 should be fine, since because of some server side issue the save may fail. 
So seems good.
