### ISSUE TITLE
What type of http response the client will get here? If 500 then we need to handle it and send 400 or similar maybe?

### ISSUE THREAD

**Issue by JobaerChowdhury** [simantaturja/CRUD-REST-API-SpringBoot#4]
https://github.com/simantaturja/CRUD-REST-API-SpringBoot/blob/01a783634013147cf848bb8595a8b029e2795376/src/main/java/com/example/crudrestapi/controller/AuthorController.java#L61

**Comment by simantaturja** [comment]
I am not sure what status code does "Exception" return but BadCredentialException itself returns 401. I am fixing this and send 401 from this exception block manually. Is it okay?

**Comment by JobaerChowdhury** [comment]
Sounds good.
