### ISSUE TITLE
Can we somehow decouple StoryService.createStory() from the UserDetails

### ISSUE THREAD

**Issue by JobaerChowdhury** [simantaturja/CRUD-REST-API-SpringBoot#5]
Right now it is coupled with the spring security UserDetails class. Maybe we should think about how to decouple this and improve the design. 

Lets imagine we want to separate the service in another jar/module for some reason -- and we don't want to add the spring security dependency there.

**Comment by JobaerChowdhury** [comment]
Same for the other methods like deleteStoryById.

**Comment by simantaturja** [comment]
I guess, writing a separate middleware will solve the issue.

**Comment by simantaturja** [comment]
Any thoughts or suggestions?

**Comment by JobaerChowdhury** [comment]
Yes, some sort of filter which will populate story with the username before sending it to the service.
